# Generated by Django 4.0.2 on 2022-02-27 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='holds the name of the car', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='holds the name of the car', max_length=200)),
                ('model', models.CharField(choices=[('v8', 'v_8'), ('v6', 'v_6'), ('v4', 'v_4')], max_length=50)),
                ('serial_number', models.PositiveBigIntegerField(unique=True)),
                ('manufacture_date', models.DateTimeField()),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_manufacturers', to='car.manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
