# Generated by Django 4.0.2 on 2022-03-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(to='car.Feature'),
        ),
    ]
