# Generated by Django 4.0.2 on 2022-03-03 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(related_name='car_features', to='car.Feature'),
        ),
        migrations.CreateModel(
            name='CarProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_profile', to='car.car')),
            ],
        ),
    ]
